Repository AppDevOrganization/5A6-group-project, pull requests merged in 2023-11, with the labels that each got.

#32 Added OverviewScreen and Navigation dependency
  app/build.gradle.kts
  app/src/main/java/com/example/emptyactivity/BankDestinations.kt
  app/src/main/java/com/example/emptyactivity/MainActivity.kt
  app/src/main/java/com/example/emptyactivity/OverviewScreen.kt
  app/src/main/java/com/example/emptyactivity/components/BankTabRow.kt
  app/src/main/java/com/example/emptyactivity/data/BankData.kt
Labels: enhancement

#39 Added cards and theme to OverviewScreen
  app/src/main/java/com/example/emptyactivity/MainActivity.kt
  app/src/main/java/com/example/emptyactivity/OverviewScreen.kt
  app/src/main/java/com/example/emptyactivity/components/BankTabRow.kt
  app/src/main/java/com/example/emptyactivity/data/BankData.kt
  app/src/main/java/com/example/emptyactivity/ui/theme/Color.kt
  app/src/main/java/com/example/emptyactivity/ui/theme/Theme.kt
  app/src/main/java/com/example/emptyactivity/ui/theme/Type.kt
  app/src/main/res/drawable/accounts.png
  app/src/main/res/font/notoserifolduyghur_regular.ttf
Labels: enhancement

#37 Navigation drawer implemented
  app/src/main/java/com/example/emptyactivity/MainActivity.kt
Labels: enhancement

#38 Logo Screen in launching the app
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/emptyactivity/MainActivity.kt
  app/src/main/java/com/example/emptyactivity/StartupScreen.kt
  app/src/main/res/drawable/cjjlogo.png
Labels: enhancement

#45 Added Chequing and Savings screens
  app/src/main/java/com/example/emptyactivity/AccountScreen.kt
  app/src/main/java/com/example/emptyactivity/BankDestinations.kt
  app/src/main/java/com/example/emptyactivity/MainActivity.kt
  app/src/main/java/com/example/emptyactivity/ui/theme/Shape.kt
  app/src/main/java/com/example/emptyactivity/ui/theme/Theme.kt
  app/src/main/java/com/example/emptyactivity/ui/theme/Type.kt
  app/src/main/res/drawable/cheque.png
  app/src/main/res/drawable/piggy_bank.png
Labels: enhancement, ui

#58 Changed navbar and added Credit Account screen
  app/build.gradle.kts
  app/src/main/java/com/example/emptyactivity/AccountScreen.kt
  app/src/main/java/com/example/emptyactivity/MainActivity.kt
  app/src/main/java/com/example/emptyactivity/components/BankTabRow.kt
  app/src/main/java/com/example/emptyactivity/components/NavItem.kt
  app/src/main/java/com/example/emptyactivity/data/BankData.kt
  app/src/main/java/com/example/emptyactivity/home/OverviewScreen.kt
  app/src/main/res/drawable/credit_card.png
Labels: enhancement, ui

#56 Update README
  README.md
Labels: ui

#67 Added accessibility features in navbar, Overview, Account, Signup and Login screens
  app/src/main/java/com/example/emptyactivity/AccountScreen.kt
  app/src/main/java/com/example/emptyactivity/LoginPage.kt
  app/src/main/java/com/example/emptyactivity/MainActivity.kt
  app/src/main/java/com/example/emptyactivity/SignupPage.kt
  app/src/main/java/com/example/emptyactivity/home/OverviewScreen.kt
Labels: enhancement, ui
