Repository AppDevOrganization/5A6-group-project, pull requests merged in 2023-12, with the labels that each got.

#101 Transfer logic implementation
  app/src/main/java/com/example/cjj/AccountsViewModel.kt
  app/src/main/java/com/example/cjj/MainActivity.kt
  app/src/main/java/com/example/cjj/data/AccountsRepository.kt
  app/src/main/java/com/example/cjj/data/BankData.kt
Labels: enhancement, ui

#105 Add spotless implementation and upgrade sdk/gradle
  .editorconfig
  app/build.gradle.kts
  app/google-services.json
  build.gradle.kts
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle.kts
Labels: enhancement, data

#108 Firebase set up
  .gitignore
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/cjj/CJJApp.kt
  app/src/main/java/com/example/cjj/LoginPage.kt
  app/src/main/java/com/example/cjj/MainActivity.kt
  app/src/main/java/com/example/cjj/SignupPage.kt
  app/src/main/java/com/example/cjj/data/AppModule.kt
  app/src/main/java/com/example/cjj/data/AuthRepository.kt
  app/src/main/java/com/example/cjj/data/AuthRepositoryFirebase.kt
  app/src/main/java/com/example/cjj/data/AuthViewModel.kt
  app/src/main/java/com/example/cjj/data/AuthViewModelFactory.kt
  app/src/main/java/com/example/cjj/data/ResultAuth.kt
  app/src/main/java/com/example/cjj/data/User.kt
  app/src/main/java/com/example/emptyactivity/data/UserPreferencesRepository.kt
  build.gradle.kts
Labels: enhancement, ui, data

#112 Added more accessibility features to the Account, Login, Sign-up, and Transfer screens
  app/google-services.json
  app/src/main/java/com/example/cjj/AccountScreen.kt
  app/src/main/java/com/example/cjj/LoginPage.kt
  app/src/main/java/com/example/cjj/MainActivity.kt
  app/src/main/java/com/example/cjj/SignupPage.kt
Labels: enhancement, ui

#113 Firebase
  app/src/main/java/com/example/cjj/BankDestinations.kt
  app/src/main/java/com/example/cjj/LoginPage.kt
  app/src/main/java/com/example/cjj/MainActivity.kt
  app/src/main/java/com/example/cjj/ResetPasswordPage.kt
  app/src/main/java/com/example/cjj/SignupPage.kt
  app/src/main/java/com/example/cjj/data/AuthRepository.kt
  app/src/main/java/com/example/cjj/data/AuthRepositoryFirebase.kt
  app/src/main/java/com/example/cjj/data/AuthViewModel.kt
  app/src/main/res/drawable/password_not_visible.png
  app/src/main/res/drawable/password_visible.png
  app/src/main/res/values/strings.xml
Labels: enhancement, ui, data

#114 Refactored the design and improved sorting feature
  app/src/main/java/com/example/cjj/AccountScreen.kt
  app/src/main/java/com/example/cjj/LoginPage.kt
  app/src/main/java/com/example/cjj/MainActivity.kt
  app/src/main/java/com/example/cjj/ResetPasswordPage.kt
  app/src/main/java/com/example/cjj/SignupPage.kt
  app/src/main/java/com/example/cjj/data/TransactionsRepository.kt
  app/src/main/java/com/example/cjj/data/UserPreferencesRepository.kt
  app/src/main/res/drawable/add_user.png
  app/src/main/res/drawable/login.png
  app/src/main/res/drawable/reset_password.png
  app/src/main/res/drawable/transfer.png
Labels: bug, enhancement, ui, data

#115 Advanced feature: Animations in Compose
  app/src/main/java/com/example/cjj/AccountScreen.kt
  app/src/main/java/com/example/cjj/LoginPage.kt
  app/src/main/java/com/example/cjj/MainActivity.kt
  app/src/main/java/com/example/cjj/home/OverviewScreen.kt
Labels: enhancement, ui

#116 Added comments and fixed a bug
  app/src/main/java/com/example/cjj/AccountScreen.kt
  app/src/main/java/com/example/cjj/LoginPage.kt
  app/src/main/java/com/example/cjj/data/BankData.kt
  app/src/main/java/com/example/cjj/home/OverviewScreen.kt
Labels: bug, documentation
